"""Added region and city

Revision ID: 0f08f8a0380c
Revises: 9487379b656e
Create Date: 2026-03-07 04:59:12.008575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f08f8a0380c'
down_revision = '9487379b656e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Click', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
