"""Update click schema

Revision ID: 9487379b656e
Revises: b176bb5c8efc
Create Date: 2026-03-02 18:50:42.033597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9487379b656e'
down_revision = 'b176bb5c8efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Click', schema=None) as batch_op:
        batch_op.drop_column('os')
        batch_op.drop_column('browser')

    # ### end Alembic commands ###
